-- Adicionando campos à tabela CMA_GD
ALTER TABLE CMA_GD ADD COLUMN id_gtw INTEGER;
ALTER TABLE CMA_GD ADD COLUMN id_sub INTEGER;

-- Adicionando campos à tabela EQP_MODBUS_IP
ALTER TABLE EQP_MODBUS_IP ADD COLUMN id_hdw INTEGER;
ALTER TABLE EQP_MODBUS_IP ADD COLUMN name_hdw TEXT;
ALTER TABLE EQP_MODBUS_IP ADD COLUMN type_sen TEXT;
ALTER TABLE EQP_MODBUS_IP ADD COLUMN model_sen TEXT;
ALTER TABLE EQP_MODBUS_IP ADD COLUMN name_sen TEXT;
ALTER TABLE EQP_MODBUS_IP ADD COLUMN id_man INTEGER;

-- Adicionando campos à tabela DP_MODBUS_IP
ALTER TABLE DP_MODBUS_IP ADD COLUMN phase_reg_mod TEXT;
ALTER TABLE DP_MODBUS_IP ADD COLUMN circuitBreakerManeuverType_reg_mod TEXT;
ALTER TABLE DP_MODBUS_IP ADD COLUMN bushingSide_reg_mod TEXT;
ALTER TABLE DP_MODBUS_IP ADD COLUMN id_reg_reg_mod INTEGER;
ALTER TABLE DP_MODBUS_IP ADD COLUMN name_reg_reg_mod TEXT;
ALTER TABLE DP_MODBUS_IP ADD COLUMN id_sen_reg_mod INTEGER;
ALTER TABLE DP_MODBUS_IP ADD COLUMN name_sen_reg_mod TEXT;

---
